package Mapeo;
// Generated 8/03/2016 05:51:11 PM by Hibernate Tools 4.3.1



/**
 * ContraseniaId generated by hbm2java
 */
public class ContraseniaId  implements java.io.Serializable {


     private int idContrasenia;
     private int idUsuario;

    public ContraseniaId() {
    }

    public ContraseniaId(int idContrasenia, int idUsuario) {
       this.idContrasenia = idContrasenia;
       this.idUsuario = idUsuario;
    }
   
    public int getIdContrasenia() {
        return this.idContrasenia;
    }
    
    public void setIdContrasenia(int idContrasenia) {
        this.idContrasenia = idContrasenia;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContraseniaId) ) return false;
		 ContraseniaId castOther = ( ContraseniaId ) other; 
         
		 return (this.getIdContrasenia()==castOther.getIdContrasenia())
 && (this.getIdUsuario()==castOther.getIdUsuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdContrasenia();
         result = 37 * result + this.getIdUsuario();
         return result;
   }   


}


