package Mapeo;
// Generated 8/03/2016 05:51:11 PM by Hibernate Tools 4.3.1



/**
 * Contrasenia generated by hbm2java
 */
public class Contrasenia  implements java.io.Serializable {


     private ContraseniaId id;
     private int contrasenia;

    public Contrasenia() {
    }

    public Contrasenia(ContraseniaId id, int contrasenia) {
       this.id = id;
       this.contrasenia = contrasenia;
    }
   
    public ContraseniaId getId() {
        return this.id;
    }
    
    public void setId(ContraseniaId id) {
        this.id = id;
    }
    public int getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(int contrasenia) {
        this.contrasenia = contrasenia;
    }




}


