package Mapeo;
// Generated 15/03/2016 04:46:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private int idLog;
     private Usuario usuario;
     private Date fecha;

    public Login() {
    }

	
    public Login(int idLog) {
        this.idLog = idLog;
    }
    public Login(int idLog, Usuario usuario, Date fecha) {
       this.idLog = idLog;
       this.usuario = usuario;
       this.fecha = fecha;
    }
   
    public int getIdLog() {
        return this.idLog;
    }
    
    public void setIdLog(int idLog) {
        this.idLog = idLog;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


